
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PTONDAPERTA = 4;
  public static final int MAGGIOREUGUALE = 24;
  public static final int PTONDACHIUSA = 5;
  public static final int AND = 27;
  public static final int MINORE = 21;
  public static final int IDENT = 32;
  public static final int ELSE = 8;
  public static final int UGUALE = 26;
  public static final int OR = 28;
  public static final int WHILE = 9;
  public static final int MENOUGUALE = 12;
  public static final int MINOREUGUALE = 22;
  public static final int NOT = 29;
  public static final int PIU = 16;
  public static final int PERUGUALE = 13;
  public static final int INTCONST = 31;
  public static final int MODULO = 20;
  public static final int IF = 7;
  public static final int DIVISO = 19;
  public static final int MODULOUGUALE = 15;
  public static final int MENO = 17;
  public static final int DIVISOUGUALE = 14;
  public static final int PVIRGOLA = 6;
  public static final int ASSEGN = 10;
  public static final int EOF = 0;
  public static final int PGRAFFAPERTA = 2;
  public static final int MAGGIORE = 23;
  public static final int DIVERSO = 25;
  public static final int error = 1;
  public static final int PGRAFFACHIUSA = 3;
  public static final int PIUGUALE = 11;
  public static final int UMENO = 30;
  public static final int PER = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PGRAFFAPERTA",
  "PGRAFFACHIUSA",
  "PTONDAPERTA",
  "PTONDACHIUSA",
  "PVIRGOLA",
  "IF",
  "ELSE",
  "WHILE",
  "ASSEGN",
  "PIUGUALE",
  "MENOUGUALE",
  "PERUGUALE",
  "DIVISOUGUALE",
  "MODULOUGUALE",
  "PIU",
  "MENO",
  "PER",
  "DIVISO",
  "MODULO",
  "MINORE",
  "MINOREUGUALE",
  "MAGGIORE",
  "MAGGIOREUGUALE",
  "DIVERSO",
  "UGUALE",
  "AND",
  "OR",
  "NOT",
  "UMENO",
  "INTCONST",
  "IDENT"
  };
}

